route:
    receiver: 'slack'

receivers:
    - name: 'slack'
      slack_configs:
          - send_resolved: true
            channel: '${slack_channel}'
            api_url: '${slack_url}'
    - name: 'opsgenie'
      opsgenie_configs:
        - api_key: '${opsgenie_api_key}'
          tags: sla_${environment},ecs,client_${project}
