global:
  slack_api_url: ${slack_url}

route:
  receiver: 'slack'
  routes:
    - receiver: slack
      match:
        severity: warning
    - receiver: 'opsgenie'
      match:
        severity: critical
    - receiver: 'opsgenie-heartbeat'
      match:
        alertname: DeadMansSwitch
      group_wait: 1s
      group_interval: 1s
      repeat_interval: 1s
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 12h
receivers:
  - name: 'slack'
    slack_configs:
      - username: ${project}-${environment}-ecs
        send_resolved: true
        channel: '${slack_channel}'
  - name: 'opsgenie'
    opsgenie_configs:
      - send_resolved: true
        api_key: '${opsgenie_api_key}'
        tags: sla_${environment},ecs,client_${project}
  - name: 'opsgenie-heartbeat'
    webhook_configs:
    - url: 'https://api.opsgenie.com/v2/heartbeats/${opsgenie_heartbeat}/ping?apiKey=${opsgenie_api_key}'
      send_resolved: true
